### ISSUE TITLE
problems cloning

### ISSUE THREAD

**Issue by dannienuc** [ColaMakerspace/ColaMakerspace.github.io#4]
Anyone have a guess why I wouldn't be able to clone the repo to my windows github desktop app?

**Comment by DallasEpperson** [comment]
Can you provide any error messages?

**Comment by dannienuc** [comment]
Disregard, it was a Windows 10 issue with CFA. Apparently the new update to Win10 is even more evil that normal about preventing the user-space from being effectively utilized.
